# Generated by Django 6.0 on 2025-12-04 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / No especifica')], default='O', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado_fisiologico', models.CharField(choices=[('NORMAL', 'Sin embarazo ni lactancia'), ('EMBARAZO', 'Embarazo'), ('LACTANCIA', 'Lactancia')], default='NORMAL', max_length=10)),
                ('peso_actual_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('objetivo_peso_tipo', models.CharField(choices=[('MANTENER', 'Mantener peso'), ('BAJAR', 'Bajar de peso'), ('SUBIR', 'Subir de peso')], default='MANTENER', max_length=10)),
                ('peso_objetivo_kg', models.DecimalField(blank=True, decimal_places=2, help_text='peso objetivo aproximado en kg', max_digits=5, null=True)),
                ('tipo_dieta', models.CharField(choices=[('OMNIVORO', 'Omnívoro'), ('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano'), ('PESCETARIANO', 'Pescetariano'), ('FLEXITARIANO', 'Flexitariano'), ('CARNIVORO', 'Alta en carnes')], default='OMNIVORO', max_length=20)),
                ('subtipo_vegetariano', models.CharField(choices=[('NINGUNO', 'Ninguno'), ('OVOLACTO', 'Ovolactovegetariano'), ('OVO', 'Ovovegetariano'), ('LACTO', 'Lactovegetariano'), ('CRUDIVEGANO', 'Crudivegano'), ('FRUGIVORO', 'Frugívoro')], default='NINGUNO', max_length=20)),
                ('calorias_mantenimiento', models.PositiveIntegerField(blank=True, help_text='estimacion de kcal/dia para mantener el peso actual', null=True)),
                ('factor_objetivo_calorias', models.DecimalField(blank=True, decimal_places=2, help_text='multiplicador sobre mantenimiento, ej 0.8, 1.0, 1.2', max_digits=3, null=True)),
                ('calorias_objetivo_diarias', models.PositiveIntegerField(blank=True, help_text='objetivo final de kcal/dia', null=True)),
                ('culturas_alimentarias', models.ManyToManyField(blank=True, help_text='patrones de comida segun cultura o region', to='core.dietacultural')),
                ('nutricionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.nutricionista')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
