# Generated by Django 6.0 on 2025-12-04 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('indice_glucemico', models.PositiveSmallIntegerField(blank=True, help_text='0 a 100 aprox, bajo <55, medio 56-69, alto >=70', null=True)),
                ('hierro_mg', models.DecimalField(blank=True, decimal_places=2, help_text='hierro por 100 g (mg)', max_digits=5, null=True)),
                ('tipo_hierro', models.CharField(choices=[('NINGUNO', 'No aplica / desconocido'), ('HEME', 'Hierro hemínico (animal)'), ('NO_HEME', 'Hierro no hemínico (vegetal)')], default='NINGUNO', max_length=10)),
                ('b12_ug', models.DecimalField(blank=True, decimal_places=2, help_text='vitamina B12 por 100 g (µg)', max_digits=5, null=True)),
                ('folatos_ug', models.DecimalField(blank=True, decimal_places=1, help_text='folatos por 100 g (µg)', max_digits=6, null=True)),
                ('vitamina_c_mg', models.DecimalField(blank=True, decimal_places=2, help_text='vitamina C por 100 g (mg)', max_digits=5, null=True)),
                ('inhibe_absorcion_hierro', models.BooleanField(default=False, help_text='ej: te, cafe, algunos lacteos segun el contexto')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='diagnostico_anemia_detalle',
            field=models.CharField(blank=True, help_text='ej: anemia hemolítica autoinmune, talasemia beta mayor, etc', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_diabetico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_b12_ug_dia',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='meta diaria de vitamina B12 en µg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_folatos_ug_dia',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='meta diaria de folatos en µg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_hierro_mg_dia',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='meta diaria de hierro en mg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rango_ayunas_max',
            field=models.PositiveSmallIntegerField(default=110, help_text='limite superior sugerido para glucemia en ayunas (mg/dL)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rango_ayunas_min',
            field=models.PositiveSmallIntegerField(default=70, help_text='limite inferior sugerido para glucemia en ayunas (mg/dL)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_anemia',
            field=models.CharField(choices=[('NINGUNA', 'Sin anemia conocida'), ('FERROPENICA', 'Ferropénica'), ('MEGALOB_B12', 'Megaloblástica por déficit de B12'), ('MEGALOB_FOL', 'Megaloblástica por déficit de folatos'), ('PERNICIOSA', 'Perniciosa'), ('HEMOLITICA', 'Hemolítica'), ('FALCIFORME', 'Falciforme / drepanocítica'), ('APLASTICA', 'Aplásica'), ('CRONICA', 'Por enfermedad crónica'), ('TALASEMIA', 'Talasemia')], default='NINGUNA', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_diabetes',
            field=models.CharField(choices=[('NINGUNA', 'Sin diabetes'), ('T1', 'Diabetes tipo 1'), ('T2', 'Diabetes tipo 2'), ('G', 'Gestacional'), ('OTRA', 'Otra')], default='NINGUNA', max_length=20),
        ),
        migrations.CreateModel(
            name='EstudioLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HB', 'Hemoglobina'), ('FERRITINA', 'Ferritina'), ('HEMATOCRITO', 'Hematocrito'), ('OTRO', 'Otro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidad', models.CharField(default='g/dL', max_length=20)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('momento', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('SNACK', 'Snack')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_comidas/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_comida', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionGlucemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('valor_mg_dl', models.DecimalField(decimal_places=1, max_digits=5)),
                ('contexto', models.CharField(choices=[('AYUNAS', 'En ayunas'), ('PRE_COMIDA', 'Antes de comer'), ('POST_2H', '2 horas despues de comer'), ('ANTES_DORMIR', 'Antes de dormir'), ('OTRO', 'Otro')], default='AYUNAS', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_glucemia', to='core.paciente')),
                ('registro_comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.registrocomida')),
            ],
        ),
        migrations.CreateModel(
            name='ItemComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcion_gramos', models.DecimalField(decimal_places=1, max_digits=6)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alimento')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.registrocomida')),
            ],
        ),
    ]
