# Generated by Django 6.0 on 2025-12-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alimento_paciente_diagnostico_anemia_detalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='carbohidratos',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='folatos_ug',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='grasas',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='inhibe_absorcion_hierro',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proteinas',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='tipo_hierro',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_c_mg',
        ),
        migrations.RemoveField(
            model_name='medicionglucemia',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='medicionglucemia',
            name='registro_comida',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='altura_cm',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='calorias_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='culturas_alimentarias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='diagnostico_anemia_detalle',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='es_diabetico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado_fisiologico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='factor_objetivo_calorias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='objetivo_folatos_ug_dia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='peso_actual_kg',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='peso_objetivo_kg',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rango_ayunas_max',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rango_ayunas_min',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='subtipo_vegetariano',
        ),
        migrations.RemoveField(
            model_name='registrocomida',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='alimento',
            name='carbohidratos_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='alimento',
            name='grasas_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteinas_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso_actual',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='talla_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='m', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='b12_ug',
            field=models.DecimalField(decimal_places=2, default=0, help_text='µg / 100 g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.DecimalField(decimal_places=1, help_text='kcal / 100 g', max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='hierro_mg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='mg / 100 g', max_digits=5),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='indice_glucemico',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0–100 aprox. Bajo <55, medio 55–69, alto ≥70', null=True),
        ),
        migrations.AlterField(
            model_name='itemcomida',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alimento'),
        ),
        migrations.AlterField(
            model_name='itemcomida',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registrocomida'),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='contexto',
            field=models.CharField(blank=True, help_text='ej: ayunas, posprandial...', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='calorias_objetivo_diarias',
            field=models.IntegerField(blank=True, help_text='kcal/día', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.nutricionista'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo_b12_ug_dia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo_hierro_mg_dia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo_peso_tipo',
            field=models.CharField(choices=[('BAJAR', 'Bajar de peso'), ('MANTENER', 'Mantener peso'), ('SUBIR', 'Subir de peso')], default='MANTENER', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_anemia',
            field=models.CharField(choices=[('NINGUNA', 'Sin anemia'), ('FERROPENICA', 'Anemia ferropénica'), ('MEGALOBLASTICA', 'Anemia megaloblástica'), ('HEMOLITICA', 'Anemia hemolítica')], default='NINGUNA', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_diabetes',
            field=models.CharField(choices=[('NINGUNA', 'Sin diabetes'), ('TIPO1', 'Diabetes tipo 1'), ('TIPO2', 'Diabetes tipo 2'), ('OTRO', 'Otra')], default='NINGUNA', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_dieta',
            field=models.CharField(choices=[('OMNIVORO', 'Omnívoro'), ('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano'), ('CARNIVORO', 'Carnívoro')], default='OMNIVORO', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comidas'),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='momento',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
