# Generated by Django 6.0 on 2025-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_alimento_carbohidratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='calorias_alcohol',
            field=models.DecimalField(decimal_places=1, default=0, help_text='kcal de alcohol / 100 g', max_digits=6),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_actividad',
            field=models.CharField(choices=[('1.20', 'Sedentario (poco o nada de ejercicio)'), ('1.38', 'Ligero (1–3 días/semana)'), ('1.55', 'Moderado (3–5 días/semana)'), ('1.73', 'Intenso (6–7 días/semana)'), ('1.90', 'Muy intenso (2 entrenos/día)')], default='1.38', help_text='factor de actividad para Mifflin', max_length=5),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_calorias_alcohol',
            field=models.IntegerField(blank=True, help_text='kcal de alcohol/día (límite)', null=True),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='notas',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
