# Generated by Django 6.0 on 2025-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alimento_calorias_alcohol_paciente_nivel_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='calorias_alcohol',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nivel_actividad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='objetivo_calorias_alcohol',
        ),
        migrations.AddField(
            model_name='alimento',
            name='es_bebida_alcoholica',
            field=models.BooleanField(default=False, help_text='Marcar si la mayor parte de las calorias vienen del alcohol (vino, cerveza, etc.)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='factor_actividad',
            field=models.DecimalField(decimal_places=2, default=1.4, help_text='1.20 sedentario · 1.40 ligero · 1.60 moderado · 1.80 alto', max_digits=3),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
