# Generated by Django 6.0 on 2025-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_alimento_calorias_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='calorias_objetivo_diarias',
            field=models.IntegerField(blank=True, help_text='kcal/día (calculado automáticamente)', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='factor_actividad',
            field=models.DecimalField(decimal_places=2, default=1.4, help_text='Ej: 1.2 sedentario, 1.5 moderado, 1.7 muy activo', max_digits=3),
        ),
    ]
