# Generated by Django 6.0 on 2025-12-04 21:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_calorias_objetivo_diarias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='calorias_objetivo_diarias',
            field=models.IntegerField(blank=True, help_text='kcal/día (se calcula automático)', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='factor_actividad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.40'), help_text='Ej: 1.2 sedentario, 1.4 ligero, 1.6 moderado, 1.8 muy activo', max_digits=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nutricionista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.nutricionista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='comidas/'),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='momento',
            field=models.CharField(choices=[('DES', 'Desayuno'), ('ALM', 'Almuerzo'), ('MER', 'Merienda'), ('CEN', 'Cena'), ('SNK', 'Snack')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
