# Generated by Django 6.0 on 2025-12-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paciente_calorias_objetivo_diarias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocomida',
            options={'ordering': ['-fecha', '-momento', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='registrocomida',
            unique_together={('paciente', 'fecha', 'momento')},
        ),
        migrations.AlterField(
            model_name='itemcomida',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.registrocomida'),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='momento',
            field=models.CharField(choices=[('DES', 'Desayuno'), ('ALM', 'Almuerzo'), ('MER', 'Merienda'), ('CEN', 'Cena'), ('SNA', 'Snack')], max_length=3),
        ),
        migrations.AlterField(
            model_name='registrocomida',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='registrocomida',
            name='foto',
        ),
    ]
