# Generated by Django 6.0 on 2025-12-05 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_registrocomida_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField()),
                ('visible_para_paciente', models.BooleanField(default=True, help_text='Si está tildado, en el futuro se podría mostrar en el panel del paciente.')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_escritas', to='core.nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_progreso', to='core.paciente')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
