# Generated by Django 6.0 on 2025-12-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notaprogreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomida',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto opcional del plato o comida.', null=True, upload_to='comidas/'),
        ),
    ]
