# Generated by Django 6.0 on 2025-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registrocomida_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='gramos_alcohol_100g',
            field=models.DecimalField(decimal_places=1, default=0, help_text='g de alcohol puro aprox. por 100 ml (ABV × 0,8)', max_digits=6),
        ),
    ]
